# Generated by Django 2.2 on 2019-04-08 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 0, 4, 27, 575824)),
        ),
        migrations.AddField(
            model_name='todo',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 0, 4, 27, 575824)),
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default='insert description in here', max_length=3000),
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 10, 3, 4, 27, 575824)),
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('1', 'Todo'), ('2', 'Doing'), ('3', 'Done')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='todo',
            name='tag_list',
            field=models.ManyToManyField(to='api.Tag'),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='Sample Title', max_length=200, unique=True),
        ),
    ]
