# Generated by Django 2.2 on 2019-04-08 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190409_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 3, 17, 36, 543977)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 3, 17, 36, 543977)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 10, 6, 17, 36, 543977)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default='Sample Title2', max_length=200, unique=True),
        ),
    ]
