# Generated by Django 2.2 on 2019-04-07 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketlist',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
