# Generated by Django 2.2 on 2019-04-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_childlist_members_postactivity_tag_todolist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
