# Generated by Django 2.2 on 2019-04-08 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190408_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postactivity',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member'),
        ),
    ]
