# Generated by Django 2.2 on 2019-04-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190408_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postactivity',
            name='members',
        ),
    ]
