# Generated by Django 2.2 on 2019-04-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_postactivity_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChildList',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
