# Generated by Django 2.2 on 2019-04-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190408_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostActivity',
        ),
    ]
