# Generated by Django 2.2 on 2019-04-08 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_postactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
    ]
