# Generated by Django 2.2 on 2019-04-08 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190408_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='postactivity',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member'),
            preserve_default=False,
        ),
    ]
